### ISSUE TITLE
Slow performance and suspicious memory behavior on large runs

### ISSUE THREAD

**Issue by peterscherpelz** [ModernElectron/WarpX#164] opened 2022-04-05 00:06 UTC
When running a few runs with embedded boundaries and ~350 million particles on 1x A100 80GB GPU, I'm seeing very poor performance.

* With 16 grids in the simulation, A100 memory usage is ~62 GB per nvtop. On some steps it is quite fast (< 1 sec/step) whereas other steps take ~25 seconds. Looking at nvtop, it looks like during each 25sec step host memory increases from ~8 GB to ~80 GB; GPU memory is basically unchanged, and at the end of the step host memory drops back to 8 GB.
* With 1 grid in the simulation, A100 memory usage is even lower (30-40 GB per nvtop), but the ~25 sec/step is consistent on every single step, and the same host memory sawtoothing from 8GB to 80 GB on every step is seen.

The profiling is also somewhat weird, as it shows that the `WarpX::Evolve::step` function takes up most of the _exclusive_ time (86.7% in the case of 16 grids), but I was under the impression almost everything that could take some performance time was timed as a separate function under this.

**Comment by peterscherpelz** [comment] 2022-04-05 00:17
Here's 100 steps of the 1-grid case:
```
TinyProfiler total time across processes [min...avg...max]: 2487 ... 2487 ... 2487

-----------------------------------------------------------------------------------------------------
Name                                                  NCalls  Excl. Min  Excl. Avg  Excl. Max   Max %
-----------------------------------------------------------------------------------------------------
WarpX::Evolve::step                                      100       2389       2389       2389  96.08%
warpx_py_particleinjection                               100      53.03      53.03      53.03   2.13%
Redistribute_partition                                   607       11.8       11.8       11.8   0.47%
ablastr::particles::deposit_charge::ChargeDeposition     305      8.598      8.598      8.598   0.35%
PhysicalParticleContainer::Evolve::GatherAndPush         299      4.995      4.995      4.995   0.20%
warpx_py_afterstep                                       100      2.228      2.228      2.228   0.09%
WarpXParticleContainer::ApplyBoundaryConditions()        400      1.889      1.889      1.889   0.08%
BackgroundMCCCollision::doCollisions()                   400       1.88       1.88       1.88   0.08%
```

**Comment by peterscherpelz** [comment] 2022-04-05 19:27
Impact of number of grids: I switched to a different input parameter set, and did four particle counts+three grid sizes: 272M/315/363M/454M particles, 1/16/64 grids. 100 steps below:

| Particle Number (M) | Grid Size | Time to completion  (sec) | Free GPU memory at end (MB) |
| ------------- | ------------- | ------------- | ------------- |
| 272 | 1  | 153 | 40858 |
| 272 | 16  | 133.5 | 18706 |
| 272 | 64  | 173 | 15000 |
| 315 | 1  | 2985 | 34838 |
| 315 | 16  | 196 | 1956 |
| 315 | 64  | 212 | 4 |
| 363 | 1  | 3185 | 32630 |
| 363 | 16  | 3817 | 4 |
| 363 | 64  | 3909 | 4 |
| 454 | 1  | 3818 | 23240 |
| 454 | 16  | DNF | OOM |
| 454 | 64  | DNF | OOM |

**Comment by peterscherpelz** [comment] 2022-04-05 19:39
@PhilMiller See my table above. It looks like 1 grid does cause time to plummet at slightly smaller particle count than the others, but 16 or 64 grids use up GPU memory faster so every grid option gets slow, and finally at even higher particle counts only the 1 grid version fits in GPU memory at all is how I interpret it. The others got errors at 454M particles:
```
amrex::Abort::0::Out of gpu memory. Free: 18599641088 Asked: 27227161280 !!!
SIGABRT
```
So it's only a tiny window where more grids win, but it does appear to exist. And it does seem that 1-grid versions are slowing down when we're only about half full on GPU memory.

These results differ just slightly from earlier results, presumably because of sensitivity to parameters. In original runs, the 16 grid had _some_ steps that went very slowly, but still showed `18704` MB free GPU global memory at the end. The 1 grid showed `40982` MB of free GPU global memory at the end but ran consistently slow, showing it's not a perfect factor of 2 cutoff vs total GPU memory for 1 grid cases.

**Comment by PhilMiller** [comment] 2022-04-05 21:36
We may want to add memory high-water-mark tracking to the AMReX allocation routines, and maybe a hook to print a backtrace when it hits some particular point

**Comment by PhilMiller** [comment] 2022-04-11 18:44
Confirmed with Kevin that the earlier scaling runs done on V100 cards with 16 GB RAM showed the performance cliff at about the (16/80 GB = ) 20% where we expected - 70M particles estimated, 60M particles observed. Lower than estimate is unsurprising because there were other constant elements that are present regardless of particle count, taking a larger percentage of the smaller device memory.

**Comment by KZhu-ME** [comment] 2022-04-11 18:48
Looking at old V100 runs, it seems like we run into a similar issue at around the number of particles we expect (V100 16GB should expect similar % memory usage at ~70 million particles). The following data comes from a 1024x1024 run.

Step # | Particle Number (M) | step/s
--|--|--
1500 | 59.8 | 5.36
1600 | 60.3 | 5.40
1700 | 60.9 | 0.39
1800 | 61.5 | 0.15

**Comment by PhilMiller** [comment] 2022-04-25 20:57
One observation is that I see the pinned memory arena occupancy oscillating wildly between empty and the entirety of GPU memory. It looks like that's used in support of particle BCs and diagnostics, among other things, presumably because they'll want to access particle data on the CPU. I'll follow up on that possibility.

**Comment by PhilMiller** [comment] 2022-04-25 22:05
After adding some more profiling sections, all of the excess time is accounted for in the line
` m_particle_boundary_buffer->gatherParticles(*mypc, amrex::GetVecOfConstPtrs(m_distance_to_eb));`

**Comment by PhilMiller** [comment] 2022-04-26 01:05
Profiling that in more detail, the excess time is almost entirely in this snippet, split across appearances for domain and embedded boundaries

```c++
                       auto np = ptile.numParticles();
                        auto dst_index = ptile_buffer.numParticles();
                        {
                        WARPX_PROFILE("ParticleBoundaryBuffer::gatherParticles::resize1");
                        ptile_buffer.resize(dst_index + np);
                        }
```
This is allocating pinned memory sufficient for every particle of a given species in the entire simulation, plus those that have already been scraped. It gets resized back down later, but the cost to allocate that much is already paid.

**Comment by PhilMiller** [comment] 2022-04-26 01:15
I could potentially add another kernel to just count the particles that would be scraped, and avoid the massive over-allocation here. That would probably constitute noticeable overhead, especially in cases where the particle count is nowhere near the memory limit, but I expect it would be quite beneficial in this case.

**Comment by roelof-groenewald** [comment] 2022-06-01 17:33
Fixed by [the above upstream PR](https://github.com/ECP-WarpX/WarpX/pull/3068).

**Closed as completed by roelof-groenewald** 2022-06-01 17:33 UTC
